### ISSUE TITLE
feature request: stringy support

### ISSUE THREAD

**Issue by hujun-open** [layeh/radius#109]
it would be quite useful to support human-friendly stringy for packet and attribute, for debug purpose, sth like:
```
Code: access-accept
Identifier: 240
Length: 112
Attributes:
    - user-name: tom
    - framed-ip-addr: 1.1.1.1
    - session-timout: 3600
```
